/*
 * Electrode Native Auth
 * Electrode react native Auth api. 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */

import AuthUserEvents from '../../src/api/AuthUserEvents';

describe('AuthUserApi', function () {
  let events;
  beforeEach(function () {
    let eventListener;
    events = new AuthUserEvents({
      registerEventListener(name, listener) {
        eventListener = listener;
      },
      emitEvent(name, data) {
        eventListener && eventListener(data);
      },
    });
  });

  describe('authUserEvent', () => {
    it('emits "authUserEvent" event', () => {
      const listener = jest.fn();
      events.addAuthUserEventEventListener(listener);
      events.emitAuthUserEvent('id');
      expect(listener).toHaveBeenCalledWith({data: 'id'});
    });
  });
});
