/*
 * Electrode Native Auth
 * Electrode react native Auth api. 
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */

import AuthUserRequests from '../../src/api/AuthUserRequests';

describe('AuthUserApi', function () {
  let requests;
  beforeEach(function () {
    let requestHandler;
    requests = new AuthUserRequests({
      registerRequestHandler(name, handler) {
        requestHandler = handler;
      },
      sendRequest(name, data) {
        requestHandler && requestHandler(data);
        return Promise.resolve(data);
      },
    });
  });

  describe('authUser', () => {
    it('sends "authUser" request', () => {
      return requests.authUser('id').then(response => {
        expect(response).toEqual({data: 'id', timeout: undefined});
      });
    });
  });
});
